services:
  - type: web
    name: vhs-termin-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_checker.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false

